### ISSUE TITLE
c++ compilation fails 

### ISSUE THREAD

**Issue by jungsook** [malte-wessel/react-custom-scrollbars#330]
Hi, 
'npm install' is failing due to compilation issue below. My c++ version is like below. Which version of compiler should I use? 

js-mac-1:simple js$ c++ --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
bsass/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -stdlib=libc++ -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/to_value.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/to_value.o ../src/libsass/src/to_value.cpp
  c++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DLIBSASS_VERSION="3.3.6"' -I/Users/js/.node-gyp/13.1.0/include/node -I/Users/js/.node-gyp/13.1.0/src -I/Users/js/.node-gyp/13.1.0/deps/openssl/config -I/Users/js/.node-gyp/13.1.0/deps/openssl/openssl/include -I/Users/js/.node-gyp/13.1.0/deps/uv/include -I/Users/js/.node-gyp/13.1.0/deps/zlib -I/Users/js/.node-gyp/13.1.0/deps/v8/include -I../src/libsass/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -stdlib=libc++ -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/units.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/units.o ../src/libsass/src/units.cpp
  c++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DLIBSASS_VERSION="3.3.6"' -I/Users/js/.node-gyp/13.1.0/include/node -I/Users/js/.node-gyp/13.1.0/src -I/Users/js/.node-gyp/13.1.0/deps/openssl/config -I/Users/js/.node-gyp/13.1.0/deps/openssl/openssl/include -I/Users/js/.node-gyp/13.1.0/deps/uv/include -I/Users/js/.node-gyp/13.1.0/deps/zlib -I/Users/js/.node-gyp/13.1.0/deps/v8/include -I../src/libsass/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -stdlib=libc++ -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/utf8_string.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/utf8_string.o ../src/libsass/src/utf8_string.cpp
  c++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DLIBSASS_VERSION="3.3.6"' -I/Users/js/.node-gyp/13.1.0/include/node -I/Users/js/.node-gyp/13.1.0/src -I/Users/js/.node-gyp/13.1.0/deps/openssl/config -I/Users/js/.node-gyp/13.1.0/deps/openssl/openssl/include -I/Users/js/.node-gyp/13.1.0/deps/uv/include -I/Users/js/.node-gyp/13.1.0/deps/zlib -I/Users/js/.node-gyp/13.1.0/deps/v8/include -I../src/libsass/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -stdlib=libc++ -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/util.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/util.o ../src/libsass/src/util.cpp
  c++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DLIBSASS_VERSION="3.3.6"' -I/Users/js/.node-gyp/13.1.0/include/node -I/Users/js/.node-gyp/13.1.0/src -I/Users/js/.node-gyp/13.1.0/deps/openssl/config -I/Users/js/.node-gyp/13.1.0/deps/openssl/openssl/include -I/Users/js/.node-gyp/13.1.0/deps/uv/include -I/Users/js/.node-gyp/13.1.0/deps/zlib -I/Users/js/.node-gyp/13.1.0/deps/v8/include -I../src/libsass/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -stdlib=libc++ -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/values.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/values.o ../src/libsass/src/values.cpp
  rm -f Release/sass.a && ./gyp-mac-tool filter-libtool libtool  -static -o Release/sass.a Release/obj.target/libsass/src/libsass/src/ast.o Release/obj.target/libsass/src/libsass/src/base64vlq.o Release/obj.target/libsass/src/libsass/src/bind.o Release/obj.target/libsass/src/libsass/src/cencode.o Release/obj.target/libsass/src/libsass/src/color_maps.o Release/obj.target/libsass/src/libsass/src/constants.o Release/obj.target/libsass/src/libsass/src/context.o Release/obj.target/libsass/src/libsass/src/cssize.o Release/obj.target/libsass/src/libsass/src/emitter.o Release/obj.target/libsass/src/libsass/src/environment.o Release/obj.target/libsass/src/libsass/src/error_handling.o Release/obj.target/libsass/src/libsass/src/eval.o Release/obj.target/libsass/src/libsass/src/expand.o Release/obj.target/libsass/src/libsass/src/extend.o Release/obj.target/libsass/src/libsass/src/file.o Release/obj.target/libsass/src/libsass/src/functions.o Release/obj.target/libsass/src/libsass/src/inspect.o Release/obj.target/libsass/src/libsass/src/json.o Release/obj.target/libsass/src/libsass/src/lexer.o Release/obj.target/libsass/src/libsass/src/listize.o Release/obj.target/libsass/src/libsass/src/memory_manager.o Release/obj.target/libsass/src/libsass/src/node.o Release/obj.target/libsass/src/libsass/src/output.o Release/obj.target/libsass/src/libsass/src/parser.o Release/obj.target/libsass/src/libsass/src/plugins.o Release/obj.target/libsass/src/libsass/src/position.o Release/obj.target/libsass/src/libsass/src/prelexer.o Release/obj.target/libsass/src/libsass/src/remove_placeholders.o Release/obj.target/libsass/src/libsass/src/sass.o Release/obj.target/libsass/src/libsass/src/sass2scss.o Release/obj.target/libsass/src/libsass/src/sass_context.o Release/obj.target/libsass/src/libsass/src/sass_functions.o Release/obj.target/libsass/src/libsass/src/sass_util.o Release/obj.target/libsass/src/libsass/src/sass_values.o Release/obj.target/libsass/src/libsass/src/source_map.o Release/obj.target/libsass/src/libsass/src/to_c.o Release/obj.target/libsass/src/libsass/src/to_value.o Release/obj.target/libsass/src/libsass/src/units.o Release/obj.target/libsass/src/libsass/src/utf8_string.o Release/obj.target/libsass/src/libsass/src/util.o Release/obj.target/libsass/src/libsass/src/values.o
  c++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/Users/js/.node-gyp/13.1.0/include/node -I/Users/js/.node-gyp/13.1.0/src -I/Users/js/.node-gyp/13.1.0/deps/openssl/config -I/Users/js/.node-gyp/13.1.0/deps/openssl/openssl/include -I/Users/js/.node-gyp/13.1.0/deps/uv/include -I/Users/js/.node-gyp/13.1.0/deps/zlib -I/Users/js/.node-gyp/13.1.0/deps/v8/include -I../../nan -I../src/libsass/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++1y -stdlib=libc++ -fno-rtti -fno-exceptions -std=c++11 -MMD -MF ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
../src/binding.cpp:246:30: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    ctx_w->success_callback->Call(0, 0);
                             ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/binding.cpp:254:28: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    ctx_w->error_callback->Call(1, argv);
                           ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
In file included from ../src/binding.cpp:3:
In file included from ../src/sass_context_wrapper.h:9:
In file included from ../src/custom_function_bridge.h:7:
../src/callback_bridge.h:162:21: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  bridge->callback->Call(argv_v8.size(), &argv_v8[0]);
                    ^
../src/callback_bridge.h:68:65: note: in instantiation of member function 'CallbackBridge<Sass_Value *, void
      *>::dispatched_async_uv_callback' requested here
    uv_async_init(uv_default_loop(), this->async, (uv_async_cb) dispatched_async_uv_callback);
                                                                ^
../src/custom_function_bridge.h:11:70: note: in instantiation of member function 'CallbackBridge<Sass_Value *,
      void *>::CallbackBridge' requested here
    CustomFunctionBridge(v8::Local<v8::Function> cb, bool is_sync) : CallbackBridge<Sass_Value*>(cb, i...
                                                                     ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
In file included from ../src/binding.cpp:3:
In file included from ../src/sass_context_wrapper.h:9:
In file included from ../src/custom_function_bridge.h:7:
../src/callback_bridge.h:162:21: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  bridge->callback->Call(argv_v8.size(), &argv_v8[0]);
                    ^
../src/callback_bridge.h:68:65: note: in instantiation of member function 'CallbackBridge<Sass_Import **, void
      *>::dispatched_async_uv_callback' requested here
    uv_async_init(uv_default_loop(), this->async, (uv_async_cb) dispatched_async_uv_callback);
                                                                ^
../src/custom_importer_bridge.h:13:70: note: in instantiation of member function 'CallbackBridge<Sass_Import
      **, void *>::CallbackBridge' requested here
    CustomImporterBridge(v8::Local<v8::Function> cb, bool is_sync) : CallbackBridge<SassImportList>(cb...
                                                                     ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
In file included from ../src/binding.cpp:3:
In file included from ../src/sass_context_wrapper.h:9:
In file included from ../src/custom_function_bridge.h:7:
../src/callback_bridge.h:110:23: warning: 'Call' is deprecated [-Wdeprecated-declarations]
      this->callback->Call(argv_v8.size(), &argv_v8[0])
                      ^
../src/binding.cpp:19:16: note: in instantiation of member function 'CallbackBridge<Sass_Import **, void
      *>::operator()' requested here
  return bridge(argv);
               ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
In file included from ../src/binding.cpp:3:
In file included from ../src/sass_context_wrapper.h:9:
In file included from ../src/custom_function_bridge.h:7:
../src/callback_bridge.h:110:23: warning: 'Call' is deprecated [-Wdeprecated-declarations]
      this->callback->Call(argv_v8.size(), &argv_v8[0])
                      ^
../src/binding.cpp:32:16: note: in instantiation of member function 'CallbackBridge<Sass_Value *, void
      *>::operator()' requested here
  return bridge(argv);
               ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
6 warnings generated.
  c++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/Users/js/.node-gyp/13.1.0/include/node -I/Users/js/.node-gyp/13.1.0/src -I/Users/js/.node-gyp/13.1.0/deps/openssl/config -I/Users/js/.node-gyp/13.1.0/deps/openssl/openssl/include -I/Users/js/.node-gyp/13.1.0/deps/uv/include -I/Users/js/.node-gyp/13.1.0/deps/zlib -I/Users/js/.node-gyp/13.1.0/deps/v8/include -I../../nan -I../src/libsass/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++1y -stdlib=libc++ -fno-rtti -fno-exceptions -std=c++11 -MMD -MF ./Release/.deps/Release/obj.target/binding/src/create_string.o.d.raw   -c -o Release/obj.target/binding/src/create_string.o ../src/create_string.cpp
../src/create_string.cpp:17:25: error: no matching constructor for initialization of 'v8::String::Utf8Value'
  v8::String::Utf8Value string(value);
                        ^      ~~~~~
/Users/js/.node-gyp/13.1.0/include/node/v8.h:3064:5: note: candidate constructor not viable: no known
      conversion from 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value' for 1st argument
    Utf8Value(const Utf8Value&) = delete;
    ^
/Users/js/.node-gyp/13.1.0/include/node/v8.h:3057:5: note: candidate constructor not viable: requires 2
      arguments, but 1 was provided
    Utf8Value(Isolate* isolate, Local<v8::Value> obj);
    ^
1 error generated.
make: *** [Release/obj.target/binding/src/create_string.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/js/proj/open/scroll/react-custom-scrollbars/examples/simple/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/13.1.0/bin/node" "/Users/js/proj/open/scroll/react-custom-scrollbars/examples/simple/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/js/proj/open/scroll/react-custom-scrollbars/examples/simple/node_modules/node-sass
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/js/.npm/_logs/2019-11-20T23_59_11_045Z-debug.log
```

**Comment by jungsook** [comment]
closing. will ask in node-sass.
